### ISSUE TITLE
a little addition 

### ISSUE THREAD

**Issue by greyfellow** [AtomicPair/wolfentext3d#1]
well first of all hi, and yeah I'm totally amazed by the and still couldn't fully understand the code but here are some game options related ideas, like maybe adding objects that could be found on the floor like a compass maybe that shows were to go but each time you use it you lose life or you lose light or maybe put a battery on it. I actually have no idea how to implement them but I feel contributing even with thoughts is helpful.

**Comment by AtomicPair** [comment]
Thanks for the feedback, @greyfellow!  I like the compass idea.

Given the modest goals for this project, I'm not quite sure yet what type of game will ultimately emerge from the whole process, but I certainly welcome any and all ideas just the same.

What other kinds of features would you like to see in the final product?

**Comment by greyfellow** [comment]
Hi, again thanks for your hard work and of course if I come up with new ideas I would definitely chare them here and I really wish this code doesn't get lost into time.

Keep up **the good work** bro (y)

**Comment by AtomicPair** [comment]
Thanks, @greyfellow!
